apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chatbot-gpu
  labels:
    app: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      restartPolicy: Always
      volumes:
        - name: chatbot-models
      containers:
        - name: chatbot
          image: MGT-BCM-001:5000/cuongnm72-llm:add-model
          ports:
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: chatbot_KEEP_ALIVE
              value: "3600" # keep model loaded for 1 hour idle
          volumeMounts:
            - name: chatbot-models
              mountPath: /root/.chatbot
