apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama-gpu
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      restartPolicy: Always
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: ollama-models-pvc
      containers:
        - name: ollama
          image: your-registry/ollama:local
          ports:
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: OLLAMA_KEEP_ALIVE
              value: "3600" # keep model loaded for 1 hour idle
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
